name: Create Artifact Package-A

on:
  push:
    branches: [ main ]
 
jobs:


  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:

      - name: Create a temporary artifact downloads folder
        run: mkdir downloads
        
      - name: Add artifacts to publish to the temp folder
        run: |
          cd downloads
          echo 'alpha'    > alpha.html
          cd ..
    
      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with: 
          name: repo-A
          path: downloads  
          
      - name: Output artifact ID
        run:  echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'    
      
      # # - name: executing remote ssh commands using password
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     password: ${{ secrets.PASSWORD }}
      #     port: ${{ secrets.PORT }}
      #     script: /usr/bin/python /home/perfsonar/read_url.py ${{ github.event.repository.name }}
      # - name: Download artifact from repo-A
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: repo-A
      #     path: downloads
      #     repository: cs1867/package-A  
      # - name: Display structure of downloaded files
      #   run: ls -R    


