# Publish GitHub workflow artifacts tutorial example
name: Publish GitHub Actions Artifacts Example

on:
  push:
    branches: [ main ]

jobs:
       
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:

      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir downloads
        
      - name: step 2 - Add artifacts to publish to the temp folder
        run: |
          cd downloads
          echo 'alpha'    > alpha.html
          cd ..
    
      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: downloads
          

      #- name: copy file via ssh password
      #  uses: appleboy/scp-action@v0.1.7
      #  with:
      #    host: ${{ secrets.HOST }}
      #    username: ${{ secrets.USERNAME }}
      #    password: ${{ secrets.PASSWORD }}
      #    port: ${{ secrets.PORT }}
      #    source: "downloads/*"
      #    target: "/tmp/"

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy script
        run: |
          ssh csacco@a27.ps.dev.internet2.edu -p 47933 'cd /home/csacco/perf-github/ && python read_url.py ${{ github.event.repository.name }}'


#      - name: executing remote ssh commands using ssh key
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          password: ${{ secrets.PASSWORD }}
#          port: ${{ secrets.PORT }}
#          script: sh hosta.sh
