name: Perfsonar Workflow Loop

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: "Create Artifact Package-A"
    branches: main
    types:
      - completed

env:
  RUN_ID: ${{ github.run_id }}

jobs:
  archive-build-artifacts:
    runs-on: ubuntu-latest

    steps:
      # Display the GitHub Run ID for debugging
      - name: Display GitHub Run ID
        run: echo '${{ github.run_id }}'

      # Define artifact types
      - name: Set Artifact Types
        id: set-artifact-types
        run: |
          echo "::set-output name=artifact-types::RHEL,DEB"

      # Loop through artifact types
      - name: Process Artifact Types
        id: process-artifact-types
        run: |
          for type in ${{ steps.set-artifact-types.outputs.artifact-types }}; do
            mkdir "downloads_$type"
            echo "RUN_ID is $RUN_ID" > "downloads_$type/README.md"
          done

      # Upload artifacts for each type
      - name: Upload Artifacts
        id: upload-artifacts
        run: |
          for type in ${{ steps.set-artifact-types.outputs.artifact-types }}; do
            echo "Uploading artifacts for $type"
            echo "Upload artifacts to repository A $type"
            uses: actions/upload-artifact@v4
            with: 
              name: "repo-A-$type"
              path: "downloads_$type"
          done

      # Output artifact ID for each type
      - name: Output Artifact ID
        id: output-artifact-id
        run: |
          for type in ${{ steps.set-artifact-types.outputs.artifact-types }}; do
            echo "Artifact ID for $type is ${{ steps.upload-artifacts.outputs.artifact-upload-id-$type }}"
          done

      # Download artifacts from repository A
      - name: Download artifacts from repository A
        uses: actions/download-artifact@v4
        with:
          name: "repo-A-RHEL"
          path: "downloads_RHEL"
          repository: cs1867/package-A

      # Display structure of downloaded files
      - name: Display structure of downloaded files
        run: ls -R 

      # Call Package B in Repository B
      - name: Call Package B in Repository B
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GIT_ACTIONS }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'cs1867',
              repo: 'package-B',
              workflow_id: 'main.yml',
              ref: 'main',
              inputs: {
                var1: '${{ github.run_id }}'
              }
            })

